name: sg2o
version: 0.4.0
description: An optimization script for SteamGifts v2.
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  path: '>=1.3.2 <2.0.0'
  html: any
dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^4.0.0
