name: sg2o
version: 0.2.21
description: An optimization script for SteamGifts v2.
environment:
  sdk: '>=1.0.0 <3.0.0'
dependencies:
  path: '>=1.3.2 <2.0.0'
  html: any
transformers:
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
