name: sg2o
version: 0.2.7
description: An optimization script for SteamGifts v2.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  path: '>=1.3.2 <2.0.0'
  html5lib: any
transformers:
- $dart2js:
    minify: true
    commandLineOptions: [--out=sg2o.user.js]
    verbose: true
dev_dependencies:
  unittest: any
